### ISSUE TITLE
Possible UI improvment

### ISSUE THREAD

**Issue by bote795** [novacourtois/runbrackets#5]
Not sure if you would like it, but my friend recommended  to try to use how google sets up the visual for the Olympics for better visual. 
Except adding a field for station 
[example](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=olympics%202016%20rio%20results%20soccer&mie=oly%2C%5B%22%2Fm%2F02vx4%22%2C6%2C%22w%22%2C1%2C%22%2Fx%2F377dnh9yb9yf5%22%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2Cnull%2C0%5D)
[![https://gyazo.com/f40cf94b93058c7644c9f17b623859e6](https://i.gyazo.com/f40cf94b93058c7644c9f17b623859e6.png)](https://gyazo.com/f40cf94b93058c7644c9f17b623859e6)

**Comment by haganbmj** [comment]
Which element of their design do you like best? The vertical pairings, the tabbed rounds? All definitely doable.

**Comment by bote795** [comment]
Personally, the tabbed rounds are what I like best, but I think adapting all of it would help, but not sure what your think.

**Comment by haganbmj** [comment]
Yeah I'll give it a go on some local tests to see what the vertical alignment looks like, I'm fearful it might be cluttered and bulky once you get to like 50+ person events. 
Tabs/filters I like. Wouldn't be tough.

**Comment by bote795** [comment]
I see what you're saying about the vertical alignment, but wouldn't it still be bulky with all the rows?  (Or half as many right?). Could possibly add another filter for the name of the player for easier search but not sure. 
Sounds good. Let's see how that looks.

**Comment by haganbmj** [comment]
Filtering by player is definitely a todo. I know Nova had some good ideas on that one.

**Comment by novacourtois** [comment]
I don't think adding tabs is necessarily an improvement. This means a TO has to click more to do the same thing. It already tells you if it's in WR or LR, but adding something like:
- semi finals, winners finals, wouldn't be too bad
- can also add (loser gets 17th, etc, but i think this just clogs up the row (not sure where to add this from a UI perspective)

Some player filtering is definitely going to happen, the table will be done with http://lorenzofox3.github.io/smart-table-website/ which is really powerful

**Comment by haganbmj** [comment]
I was more thinking of it as shortcuts for filtering by round, leaving the default view as everything.
